### ISSUE TITLE
feat(NOTIF_SMS): Faisabilité et estimation du temps

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1074]
**Situation Actuelle**

Un compte test est disponible, voir si l'outil se prête techniquement à notre besoin et le temps que ça prendrait.

**TODO**

- [x] parcours de l'interface, lecture de la documentation: <https://www.spot-hit.fr/documentation-api>
- [x] si l'outil semble faire l'affaire, test d'intégration simple de l'api (envoi d'un sms)
- [x] définir le process général de l'envoi (ex: stockage du msg en bdd, puis envoi périodique via un service consommateur, gestion des différents types d'erreur, validation des numéros?, gestion des accusés de réception? <https://www.spot-hit.fr/documentation-api#chapter3>)
- [x] estimation du temps nécessaire pour intégrer les différents mécanismes techniques
- [ ] intégration technique complète (ou par étapes, suivant ce qui a été défini)
