### ISSUE TITLE
feat(STATS_STRUCTURE): ajout motif de la demande

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1079]
**Situation Actuelle**

Actuellement le motif de la demande de domiciliation n'apparait pas dans la page statistiques structure.

**Comportement souhaité**

Après la section "Cause de l'instabilité de logement", ajouter la section "Motif principal de demande de domiciliation " avec les 3 réponses possibles : 
- Exercice des droits civils ou civiques
- Accès aux prestations sociales
- Autre raison

**TODO**

- [x] modifier le modèle des stats
- [x] mise à jour du calcul des stats
- [x] mise à jour de l'export excel
- [x] script de mise à jour des stats passées (à mutualiser entre tickets #1079, #1080 et #1081)

L'information se trouve dans `"entretien"->>'raison'`

Se baser sur `usagerRepository.countDomiciliations` pour le patch et le calcul des nouvelles stats.

**Recette PO**

Vérifier les stats et leur fonctionnement.

**Comment by Toub** [comment]
@ledugong on ne prend en compte que les actifs pour cette stats je suppose?

**Comment by ledugong** [comment]
@Toub oui pour le moment

**Comment by Toub** [comment]
@ledugong faut-il faire une modification sur le libellé, pour préciser qu'il ne s'agit que des domiciliés (sans leur ayant-droits), et si oui, laquelle?

![image](https://user-images.githubusercontent.com/367762/112963709-ed9b1000-9147-11eb-9a20-ff859063aab2.png)

**Comment by Toub** [comment]
Et aussi pour préciser que l'on ne tient compte que des actifs?

**Comment by ledugong** [comment]
@Toub peux-tu déplacer la section "motif principal" en dessous de la section "cause de l'instabilité du logement" ? Pour garder l'ordre des questions de l'entretien.

En le déplaçant ainsi, on peut garder le même libellé sans précision, comme les sections au-dessus.

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
