### ISSUE TITLE
feat(STATS_STRUCTURE): ajout sexe

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1080]
**Situation Actuelle**

Les structures demandes des stats par sexe.

**Comportement souhaité**

Sous la section "Total des domiciliés actifs + leurs ayants-droit", ajouter une section "Nombre de domiciliés actifs par sexe", puis les 2 réponses possibles : 
- Femme
- Homme

**TODO**

- [x] modifier le modèle des stats
- [x] mise à jour du calcul des stats
- [x] mise à jour de l'export excel
- [x] script de mise à jour des stats passées (à mutualiser entre tickets #1079, #1080 et #1081)

**Recette PO**

Vérifier les stats et leur fonctionnement

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
