### ISSUE TITLE
feat(STATS_STRUCTURE): ajout stats par tranche d'âge

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#1081]
**Situation Actuelle**

Nous avons actuellement déjà des stats "majeur/mineur" mais les structures veulent plus de détails avec des tranches d'âge.

**Comportement souhaité**

Modifier la section "Nombre de domiciliés actifs par tranche d'âge" en remplaçant majeur / mineur par les tranches d'âge officielles de l'INSEE (https://www.insee.fr/fr/statistiques/2381474), à savoir : 
- Moins de 15 ans
- 15-19 ans
- 20-24 ans
- 25-29 ans
- 30-34 ans
- 35-39 ans
- 40-44 ans
- 45-49 ans
- 50-54 ans
- 55-59 ans
- 60-64 ans
- 65-69 ans
- 70-74 ans
- 75 ans ou plus

**TODO**

- [x] modifier le modèle des stats
- [x] mise à jour du calcul des stats
- [x] mise à jour de l'export excel
- [x] script de mise à jour des stats passées (à mutualiser entre tickets #1079, #1080 et #1081) 

**Recette PO**

Vérifier les stats et leur fonctionnement

**Comment by Toub** [comment]
![image](https://user-images.githubusercontent.com/367762/112970021-11615480-914e-11eb-9495-54d2ff435447.png)

**Comment by Toub** [comment]
Comme convenu, on ne prend pas en compte les ayants droits pour le moment, car il faut convertir en date le champ `usager.ayantsDroits.dateNaissance`

**Comment by Toub** [comment]
La plupart des dates de naissances des ayants droits sont valides, et on pourrait les convertir en date, via:


```sql
SELECT TO_DATE(u.ayantDroit->>'dateNaissance', 'DD/MM/YYYY'), count(*) FROM 
(select jsonb_array_elements("ayantsDroits") ayantDroit from usager) as u
group by TO_DATE(u.ayantDroit->>'dateNaissance', 'DD/MM/YYYY')
order by count(*) desc ;`
```

Mais il y a quelques dates invalides, par exemple '31/11/2020'; Et aussi quelques années invalides, que l'on peut retrouver via:

```sql
SELECT SUBSTRING(u.ayantDroit->>'dateNaissance', 7, 4), count(*) FROM 
(select jsonb_array_elements("ayantsDroits") ayantDroit from usager) as u
group by SUBSTRING(u.ayantDroit->>'dateNaissance', 7, 4)
order by SUBSTRING(u.ayantDroit->>'dateNaissance', 7, 4) desc ;
```

![image](https://user-images.githubusercontent.com/367762/112972973-1ffd3b00-9151-11eb-90a4-3736424bd8a4.png)
![image](https://user-images.githubusercontent.com/367762/112973004-268bb280-9151-11eb-8abc-c3a191c69603.png)


Donc la transformation doit se faire en JS, et il faut décider que faire avec les dates invalides (les rendre null, les approximer...)

**Comment by ledugong** [comment]
Recette PO OK

**Comment by ledugong** [comment]
Recette Prod OK
