### ISSUE TITLE
info(NOTIF_SMS): ticket de suivi de la feature 

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#1094]
**Situation Actuelle**

Actuellement, les SMS ne sont pas implémentés, ce ticket a pour but de recenser les questions sur le sujet

**Comportement souhaité**

Développer un outil d'envoi de SMS qui soit utile aux structures et aux domiciliés 

**Todo**

 
- [ ] ETQ dev, je planifie l'envoi d'un SMS suite à une interaction #1097  - **1**

- [ ] ETQ domicilié, je reçois un SMS quand je reçois du courrier #1095 - **1**

- [ ] Ouvrir un endpoint permettant la mise à jour du statut d'un SMS #1096 - **1**

- [ ] ETQ dev, je renvois les SMS vers un seul et même numéro **0.5**

- [ ] ETQ **Domifa,** je dois pouvoir activer ou désactiver l'envoi de SMS pour une structure #1090 - **0.5**

- [ ] ETQ utilisateur, je peux demander à l'usager s'il veut recevoir ou non un SMS #1089 - **0.5**

- [ ] ETQ **Structure**, je peux paramétrer l'expéditeur #1092 - **0.5**

- [ ] ETQ utilisateur, je vois un historique des SMS envoyés à un usager + alertes en cas d'échec #1093 - **1**

Deuxième temps : 

- [ ] ETQ Domifa, je peux suivre le nombre d'envoi de SMS par les structures #1091 - ** > 1 **

**Pré-requis**
 Définir les templates de SMS

**Questions**

1. A quel moment de la journée envoyer les SMS ?
2. Quel comportement en cas d'échecs répétés de l'envoi d'un SMS ?
3. Combien de SMS max par usager / jour ?
4. Un utilisateur peut-il réactiver un STOP SMS ?
