### ISSUE TITLE
feat(MATOMO): tracker le nombre de connexions sur le portail usager

### ISSUE THREAD

**Issue by ledugong** [SocialGouv/domifa#2043]
**Comportement souhaité**

- [x] tracker le nombre de tentatives de connexion (toute erreur confondue)
- [x] tracker le nombre de connexions réussies
- [x] tracker le nombre de premières connexions

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [x] vérifier les crackers

**Comment by pibouu** [comment]
Matomo :
groupe => login-portail-usagers
key :
- login_success
- login_success_first_time
- login_error

**Comment by pibouu** [comment]
domifa-2043-matomo-portail-usager.dev.fabrique.social.gouv.fr

**Comment by ledugong** [comment]
Non recettable PO

**Comment by ledugong** [comment]
Devrait passer avec le fix
