### ISSUE TITLE
feat(TELEPHONE): En tant que structure je souhaite modifier le numéro des domiciliés qu'à un seul endroit 

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2402]
**Situation Actuelle**

Il y a deux champs de téléphones pour le domicilié, l'un dans l'onglet courrier, l'autre dans le dossier. Ce n'est pas maintenable. 
Les structures changent l'un mais pas l'autre.

**Comportement souhaité**

## Maquette à l'édition 
![image](https://user-images.githubusercontent.com/86293911/181460618-2bb0e916-bd07-402c-aa16-c4bc555c170f.png)

![Capture d’écran 2022-07-28 à 10 18 28](https://user-images.githubusercontent.com/86293911/181460309-7141963c-6ee0-47e9-b4d9-1a4208142a87.png)

## Maquette lecture d'information

![Capture d’écran 2022-07-28 à 10 31 02](https://user-images.githubusercontent.com/86293911/181460302-8a2385e9-5245-42e4-8063-ca565cdb74b0.png)

# Todo list

- [ ] Migrer les numéros qui se trouvent dans l'onglet courrier vers dossier (pour ceux qui n'ont pas activé les sms garder le numéro existant dans dossier)
- [ ] Migrer la question "Le demandeur souhaite-t-il recevoir des notifications par SMS (arrivée d'un courrier, échéance de domiciliation) ?" dans la partie dossier. 
- [ ] Dans le dossier intervertir le champ "numéro de téléphone" avec identifiant personnalisé 
- [ ] Supprimer la rubrique "Préférence de contact" dans l'onglet courrier
- [ ] Dans l’onglet dossier reprendre les regles de gestion instaurés dans l'onglet courrier (accepter que les téléphone numéro mobile) 
- [ ] Dans l'onglet dossier changer le wording du champ téléphone par "Numéro de téléphone portable"
- [ ] dans l’instruction de dossier, supprimer le champs numéro de téléphone pour les préférence de contact sms
- [ ] S’assurer que spot it/netsize prenne en référence les numéros du dossier et non courrier

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] Vérifier sur le Cerfa le numéro de téléphone
- [ ] Vérifier dans l'export les numéros de téléphone
- [ ] Vérifier l'instruction de dossier

Communication
- [ ] faire une com aux structures leur indiquant que seul un 06 sera accepté 
- [ ] faire une com aux structure leur indiquant que les numéros de l'onglet courrier est migre sur l'onglet dossier

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by celinelr** [comment]
A la dernière étape d'instruction de dossier ne faudrait il pas ajouter le champs "Notifications par SMS activés + OUI / NON" ?
![Capture d’écran 2022-08-05 à 11 45 32](https://user-images.githubusercontent.com/86293911/183051475-d05e2068-8e57-4fb4-b295-29e4a24d9920.png)

**Comment by celinelr** [comment]
Lorsque je fais une premiere demande ou un renouvellement si après avoir passsé la première etape et que je reviens à la première étape pour modifier mon choix pour la reception des sms
- Problème 1 :  je peux cocher oui et passer à l'étape 2 sans remplir le champs avec le numéro de téléphone. Je ne devrais pas pouvoir passer à la page suivant si le champ téléphone n'est pas rempli si la question à l'activation des SMS est oui
- Problème 2 : Si je coche non après avoir coché oui et que le champ numéro de téléphone est vide alors je ne peux pas aller à l'étape 2 de l'instruction de dossier. Le champ téléphone ne devrait pas avoir de message d'erreur 'Le numéro de téléphone est incorrect" car le champ est vide alors que je ne souhaite pas recevoir de sms


Je te laisse consulter la video pour comprendre les étapes de reproduction. 

https://user-images.githubusercontent.com/86293911/183052421-acd68c44-d0a2-42e2-a964-866093db54b3.mov

**Comment by celinelr** [comment]
Détail de la recette :

**Comment by celinelr** [comment]
Il faudrait changer le document explicatif des sms à ces deux endroits s'il te plait

<img width="1198" alt="Capture d’écran 2022-08-08 à 16 23 00" src="https://user-images.githubusercontent.com/86293911/183440627-46feb770-692c-46de-9b74-2ba105c6cf82.png">



[Document_Explicatif_Notifications_SMS.pdf](https://github.com/SocialGouv/domifa/files/9282487/Document_Explicatif_Notifications_SMS.pdf)

**Comment by celinelr** [comment]
Il faudrait changer "courrier" par "dossier"

<img width="1176" alt="Capture d’écran 2022-08-08 à 16 17 07" src="https://user-images.githubusercontent.com/86293911/183441058-1f30beb1-f9b0-400e-84ef-17c441346f45.png">

**Comment by pYassine** [comment]
Suite à des tests de non-regression j'ai remarqué qu'on a pas mit l'import dans la recette. Voici 3 éléments à valider

**Import : **
- [ ] Je ne dois pouvoir importer que des numéros de mobile
- [ ] Dans le modèle de fichier Excel proposé aux structures, à la place de "0142424242", indiquer un numéro de mobile
- [ ] Mettre à jour la documentation de l'import

**Comment by celinelr** [comment]
Manque :
- Il faudrait changer "courrier" par "dossier"
- A la dernière étape d'instruction de dossier ne faudrait il pas ajouter le champs "Notifications par SMS activés + OUI / NON"

**Comment by celinelr** [comment]
@pYassine le document à jour de l'import :
[Tutoriel_importer_vos_domiciliés.pdf](https://github.com/SocialGouv/domifa/files/9289298/Tutoriel_importer_vos_domicilies.pdf)

**Comment by celinelr** [comment]
tout me semble bon, je valide ! 
J'enverrai la communication une fois tout en production
