### ISSUE TITLE
feat(FOOTER): Maj logo ANCT

### ISSUE THREAD

**Issue by celinelr** [SocialGouv/domifa#2449]
**Situation Actuelle**

Vous trouverez ci-joint le nouveau logo de l’ANCT qu’il faudra intégrer à votre outil et autres supports au côté du logo NextGeneration EU et du logo France Relance accompagné par la mention « soutenu par l’Incubateur des Territoires de l’ANCT dans le cadre du plan France Relance » ;

Fichier original : [Financement_et_accompagnement_France_Relance_-_Pièces_justificatives.zip](https://github.com/SocialGouv/domifa/files/9597809/Financement_et_accompagnement_France_Relance_-_Pieces_justificatives.zip)

Fichier resizé 
[Logo resized.zip](https://github.com/SocialGouv/domifa/files/9597847/Logo.resized.zip)

# TODO

- [ ] Changer les logos sur le footer Domifa
- [ ] Changer les logos sur le footer de L'admin 
- [ ] Changer les logos sur le footer du portail dom

**Lien vers l'environnement de test**

Par défaut : https://domifa-preprod.dev.fabrique.social.gouv.fr/

**Recette PO**

- [ ] vérifier sur le footer Domifa les logos 
- [ ] Vérifier sur le footer de L'admin les logos
- [ ] Vérifier sur le footer du portail dom les logos

**aide/documentation tickets github**: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by celinelr** [comment]
![ANCT_AvecLeSoutienDe](https://user-images.githubusercontent.com/86293911/191054191-0ef5de25-93e2-4fa6-a4f9-edcfcc8fd9bc.jpg)

**Comment by pYassine** [comment]
@celinelr  https://domifa-fix-edit-user.dev.fabrique.social.gouv.fr/

**Comment by celinelr** [comment]
Merci je valide pour les 3 sites
