### ISSUE TITLE
debt(mongo): migration postgresql

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#793]
## Généralités

L'analyse préliminaire #925 nous aiguille vers une migration postgres progressive, rapide (pour ne pas rester trop longtemps entre 2 chaises) et économique (ressources limitées), ce qui implique:
- une phase de prototype
- intégration progressive de postgres
- pas de hasura pour le moment (trop d'impacts)
- passage sur l'infra k8s une fois que l'ensemble du projet sera migré

## Réalisé

Sur une branche (livrée en prod en sprint 20 ou 21 suivant l'avancement):

- [x] #925 analyse préliminaire
- [x] #929 proto typeorm/postgres: migration du document `stats`

## TODO

- [ ] #965 migration du document `users`
- [ ] #966 migration du document `usagers`
- [ ] #967 migration du document `structures`
- [ ] #968 migration du document `interactions`
