### ISSUE TITLE
feat(matomo): Tracker les clicks sur la page manage

### ISSUE THREAD

**Issue by pYassine** [SocialGouv/domifa#960]
**Situation Actuelle**

On ne sait pas qui clique sur quel bouton dans la page manage

**Comportement souhaité**

Page de recherche
- [ ] Tracker les clics sur les onglets
- [ ] Tracker les clics sur les filtres
- [ ] Tracker le nombre de recherche

Page profil
- [ ] Edition de procuration
- [ ] Edition de transfert
- [ ] Edition d'entretien

**Recette PO**

- [ ] Vérifier sur Matomo

__aide/documentation tickets github__: <https://github.com/SocialGouv/domifa/tree/master/_docs/github-issues.md>

**Comment by ledugong** [comment]
Recette PO
